[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/results"
  to = "/.netlify/functions/get-results"
  status = 200

[[redirects]]
  from = "/api/result"
  to = "/.netlify/functions/set-result"
  status = 200

[[redirects]]
  from = "/api/overrides"
  to = "/.netlify/functions/get-overrides"
  status = 200

[[redirects]]
  from = "/api/match-override"
  to = "/.netlify/functions/set-match-override"
  status = 200

[[redirects]]
  from = "/api/bet-override"
  to = "/.netlify/functions/set-bet-override"
  status = 200
